version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: raul
      POSTGRES_PASSWORD: raulpassword
      POSTGRES_DB: planos_aula_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: api_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=raul
      - DB_PASSWORD=raulpassword
      - DB_NAME=planos_aula_db
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: spa_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: